examples/valid/__gitlab-é__.yml
examples/valid/v4/access_requests.yaml
examples/valid/v4/models/ProjectAccessResponse.yaml
src/definition.ts
test/unit/definition.test.ts

The internal `$refs` Class of the json-schema-ref-parser library stores
paths in a URI encoded fashion. This is to prevent confusion between #
hash internal references (mentioned in the full json path) and #
characters in the filesystem path.
This commit makes sure to fetch the parsed values from the `$refs`
object from the `$refs.values()` function (instead of the
`$refs.get($ref)` function).
I got a bit confused with the internals of the lib as I expected to be
able to provide the returned values of `$Refs.paths()` to the
`$Refs.get()` function transparently. But this does not work for
filesystem paths containing special characters. The best solution is
thus to fetch the `$refs.values()` object which has decoded file path
as keys. I.e. exactly what we need.

fix: resolve accented filesystem path correctly in $RefParser lib

---

.github/workflows/release.yml
package.json

As part of #18 this is a test to try to push tarballs generated by
oclif to a Github Release.
The idea for the release process would be in two steps:
1. locally on a developer machine: bump the version, commit, tag and
publish to npm with the following command:
```
npm run publish -- 2.0.1
```
This will not create a github release anymore (due to the added
`--no-release-draft` tag passed to `np`).
2. once the tag is pushed, the CI kicks in with this [github action](https://github.com/softprops/action-gh-release)
by doing the following:
- Github draft release creation
- Upload of standalone tarballs (generated by oclif)
3. The developer needs to edit the newly created draft release to
write release notes and publish the github release 🚀

core: add release step in CI to push packed tarballs to GH release

---

README.md
src/commands/preview.ts

This is a small addition to help open up a preview directly in your
browser.

preview: add a flag to open the URL in a browser directly

---

src/api/models.ts
src/commands/deploy.ts

This change tells the TS compiler that the Bump API will always answer with an `id` field in the responses for both POST /versions & POST /previews.
It doesn't change anything feature wise but will avoid useless JS guards when using those fields.

api(bump): 'id' attribute is always present in both previews & versions responses

---

src/index.ts

This is some boilerplate code to be able to expose part of the CLI codebase in the NPM package.
For now we were only exporting a binary (the `bump` executable) and the `run` function from oclif if the NPM package was used as a library.
With this change, we can export parts of the CLI codebase in other packages (most importantly for us, in our `github-action` codebase). It was already possible to import parts of the `bump-cli` package by directly importing the full file path of each file (as we [did here for example](https://github.com/bump-sh/github-action/blob/master/src/main.ts#L2)) but it wasn't very satisfactory.
From now on, we can be clear with our intention and export the classes / functions / types that can be reused in other apps/libs.

module: export commands and types to be able to reuse parts of the CLI

---

test/unit/api.test.ts

By specifying the root path of the package.json file we can test more
precise oclif settings, especially in the generate User Agent.
Discussion initiated in https://github.com/bump-sh/cli/pull/20#discussion_r630887316

test: load the root package.json file during testing

---

README.md
src/api/index.ts
src/api/models.ts
src/command.ts
src/commands/deploy.ts
src/commands/diff.ts
src/commands/preview.ts
src/flags.ts
src/index.ts
test/commands/deploy.test.ts
test/commands/diff.test.ts

This is a new command `bump diff` which allow to fetch a documentation
change between an existing documentation and a provided definition
FILE.
```
Get a comparaison diff with your documentation from the given file or URL
USAGE
$ bump diff FILE
ARGUMENTS
FILE  Path or URL to your API documentation file. OpenAPI (2.0 to 3.1.0) and AsyncAPI (2.0)
specifications are currently supported.
OPTIONS
-b, --hub=hub      Hub id or slug. Can be provided via BUMP_HUB_ID environment variable
-d, --doc=doc      (required) Documentation public id or slug. Can be provided via BUMP_ID environment
variable
-h, --help         show CLI help
-t, --token=token  (required) Documentation or Hub token. Can be provided via BUMP_TOKEN environment
variable
EXAMPLES
Compare a potential new version with an existing …
```

feature: add a `diff` command to be able to retrieve a doc change

---

README.md

What to you think about a link to Bump help center https://help.bump.sh/ ?

Add link to Bump CLI help center

---

README.md

Following the changes of the readme on the github-action in
https://github.com/bump-sh/github-action/pull/50 we link to the
correct paragraph from the CLI readme.

readme: update the link to the Github Action diff usage

---

examples/valid/asyncapi.v2.yml
examples/valid/doc/introduction.md
src/definition.ts
test/unit/definition.test.ts

This PR adds a simple text parser to be able to parse `.md` or
`.markdown` files used as external refs (as a `$ref` in the contract
document).
With this change, our users will be able to extract big markdown
content from their parent contract document into dedicated external
files.
E.g.
```
openapi: 3.1.0
info:
title: This is a super cool API
description:
$ref: "./api-description.md"
version: "1.0"
servers:
...
paths:
...
```

feat(parser): allow markdown files to be parsed as external refs

---

README.md

Add information about `diff` command, that are displayed with `bump --help` for version 2.1.1
---
Noticed while working with last version of cli, to verify breaking changes.

Adapt Readme to version 2.1.1

---

README.md
package-lock.json
package.json
src/api/index.ts
src/commands/preview.ts
src/flags.ts

This feature adds a new flag `--live` to the `bump preview` command,
to continously update a preview at each file save.
It's very helpful when you are writing your API definition file and
want to see the result each time you save your file.
_Note: This PR depends on the backend changes in bump-sh/bump#1026_

previews: add a `--live` option to be able to do live previews

---

src/api/models.ts

This new attribute was introduced in the API here
https://developers.bump.sh/changes/a71bf771-693f-49b1-95b3-756b67e9d7bf#get-versions-parameter-200-diff_breaking

api: update Version response to include breaking information

---

README.md
src/api/models.ts
src/args.ts
src/commands/diff.ts
test/commands/diff.test.ts

For now the `diff` command only compares the given file with the
currently deployed version on Bump.
With this change, we modify the `diff` command to take a second
optional FILE parameter in order to compare two different definition
files when needed (mostly in PRs).
_Note: depends on the backend changes in bump-sh/bump#985_

diff: allow comparing two different definition files

---

src/command.ts
src/commands/deploy.ts
src/commands/diff.ts
src/commands/preview.ts
src/core/diff.ts
src/definition.ts
src/index.ts
test/commands/deploy.test.ts
test/commands/diff.test.ts
test/unit/definition.test.ts

This refactoring is done to extract command logic into dedicated
classes so they can be reused programmatically without the need use
the CLI commands (which is codesmell to do so cf
https://oclif.io/docs/running_programmatically ).
This will help to re-use the CLI logic inside our Github-Action
instead of relying on the oclif commands return content (which should
not be used).

refacto: extract the diff logic into a dedicated class

---

test/commands/diff.test.ts

Since #192, the polling period was not stubbed in the diffs tests
anymore (and thus taking 32s of waiting during tests for nothing...).
I didn't really understand why but I needed to import the core diff
from the `lib/` dir instead of the `src/` dir. 🤷

tests: fix stubbing of core diff polling period

---

README.md
src/api/index.ts
src/api/models.ts
src/commands/diff.ts
src/core/diff.ts
src/flags.ts
src/index.ts
test/commands/diff.test.ts

This commit adds a new `--format` flag to the `bump diff` command to
return the diff result in either:
- `text` format (this is the default and current behavior)
- `markdown` format. Renders a markdown formatted text
- `json` format. Renders a json object with all the diff details.
_Bonus: the PR also contains a small refactoring of types to handle
diffs in an easier fashion (Will be helpful for our “Bump diff v2” cf
#221)_

diff: add new '--format' flag to render text, markdown or JSON diff

---

src/api/index.ts
src/api/models.ts
src/commands/diff.ts
src/core/diff.ts
src/index.ts
test/commands/diff.test.ts

With this change the `bump diff` command can be used without being logged-in (without `--doc` and `--token` flags).
This allows for any given user to compare **two different API definition** files.
It makes use of the new `POST /api/v1/diffs` API available on bump.sh. (cf bump-sh/bump#1541)

diff: send 2 files diff to the new public diff endpoint

---

test/unit/api.test.ts

This is a fix for the unit test testing the CLI user agent used. When
the version is published with a tag (`-beta`) the tests were failing.
With this commit we accept any tag behind the version number. 😌

tests: fixing api unit test when cli version has a tag

---

src/api/error.ts
src/api/index.ts
src/api/models.ts
src/commands/diff.ts
src/core/diff.ts
src/flags.ts
test/commands/diff.test.ts

Now that our API has a [`formats` parameter](https://developers.bump.sh/changes#event-change-62c8d3d6-c8b9-4146-8e95-0e0819afb9c5) let's use it to retrieve only the format asked by the CLI user.

diff: send format parameter to the API calls to get diff result

---

package-lock.json
package.json
src/cli/index.ts

Cli-ux has been migrated to a new package @oclif/core which
incorporates all other oclif packages (@oclif/command and
@oclif/config).
We will migrate @oclif/command and @oclif/config in a later PR.
This will remove the `WARNING` message when users install `bump-cli`
warning them that we use a deprecated `cli-ux` package.

deps: use @oclif/core instead of cli-ux npm package

---

README.md

Since release v2.3.2 we now allow unauthenticated bump diffs. Meaning
anybody can ask for an API diff from the CLI.
The udpate in the readme was probably forgotten when we made the
change so here is a documentation update!
@jayk-u would you mind taking a look at this?

README: update `bump diff` command since we allow public diffs now

---

.github/workflows/checks.yml
README.md
package-lock.json
package.json

This commit makes the CLI require at least node v14.
It also updates packages with security issues (minor patches).
Note: v12 is EOL cf https://nodejs.org/en/about/releases/

core: minimum Node engine is now >= v14

---

src/api/models.ts
src/commands/deploy.ts
src/commands/diff.ts
src/core/diff.ts
src/flags.ts
test/commands/deploy.test.ts
test/commands/diff.test.ts

This commit adapts both the `deploy` and `diff` commands to accept a
new CLI parameter: `-B name` (or its long version `--branch=name) to
be able to deploy (or diff) a new version on a specified branch.
By default any commands running against a documentation without branch
information will affect the “default” branch.
Closes #299

branching: adapt `deploy` & `diff` commands to accept branch input

---

.github/workflows/checks.yml
src/definition.ts
test/unit/definition.test.ts

This commit is a bugfix for Windows based filesystem when external
references are defined on disk. Indeed we had a wrong regexp matchin
only unix style filesystem paths.
The fix consists of parsing windows style filesystem paths too.
I've tested it on a VM and the fix seems to work fine.

fix: send relative paths for external file system paths on Windows

---

src/api/models.ts
src/commands/diff.ts
src/core/diff.ts
src/flags.ts

When creating a public diff (non authenticated `bump diff` command),
users will now be able to provide an extra `--expires <date>`
parameter to change the default (1 day) expiration date of public
diffs.
Format of the date is in `iso8601`. The parameter can also receive
`never` value if the user doesn't want to publid diff to expire.

diff: add a `--expires` CLI parameter for public diffs

---

README.md

After some feedbacks from users, let's explicit the usage of the
`--branch` parameter directly in the README.

doc: explicit the `--branch` deploy parameter

---

src/definition.ts

Even if we don't fully support the new
version (https://www.asyncapi.com/blog/release-notes-2.6.0) we can
accept the new version contracts to be sent to bump.sh.

asyncapi: allow 2.6.0 version of AsyncAPI contracts

---

src/commands/deploy.ts
src/core/deploy.ts

This commit extracts the logic around a “Deploy” from the `Deploy`
command into a core `core/Deploy` internal class.
The changes doesn't affect any of the command behavior it only
extracts logic into a dedicated class for later improvements (notably:
multiple deploys from a directory).

refacto: extract deploy logic into a dedicated core lib

---

README.md
examples/valid/bump-api.json
package-lock.json
package.json
src/api/error.ts
src/args.ts
src/commands/deploy.ts
src/commands/diff.ts
src/commands/preview.ts
src/core/definition_directory.ts
src/core/deploy.ts
src/core/utils/file.ts
src/core/utils/prompts.ts
src/definition.ts
src/flags.ts
test/commands/deploy.test.ts
test/unit/api.test.ts

About #217 and [functional specifications](https://www.notion.so/bumpsh/Multiple-API-definitions-upload-6dd6debec355401f844992966e8b04bb) available on Notion.
This PR adds a new possibility to run `bump deploy /path/to/directory/` in order to deploy multiple API contrat files in one command.
Here is an example with two cases, first case is with a directory which has files that follow the given naming convention (with `--filename-pattern` flag), second case is with a directory which already has files that follow the naming convention but we want to add some more interactively (with `--interactive` flag).
By default if no `--filanme-pattern` flag is provided the convention will be `{slug}-api` for definition filenames.
:sparkles:

deploy: add hub directory deploy

---

package-lock.json
package.json

This adds the Oclif “warn if update available” plugin in our CLI. It
will display a warning message to users when they use an outdated CLI.
Here's the look-and-feel :

plugins: add update available warning

---

.github/workflows/release.yml
package.json

This PR contains two commits:
- First one is to rename the custom publish/release script from `npm run publish` to `npm run release`
- Second one is to fix the release build in Github CI which is broken due to the usage of `node:` namespacing in some imports we introduced...

Fix & improve release

---

src/commands/deploy.ts
src/core/utils/file.ts
test/commands/deploy.test.ts

In 2.7.0 we introduced the “hub” deployment to deploy a whole
directory. However we introduced a constrait on the input file
parameter of the `deploy` command to be an object on the
filesystem (due to the usage of `fs.statSync` function).
This commit makes sure to not crash if we pass a URL string and want
to deploy from a URL (instead of a fs filepath).

fix: deploy from a URL

---

src/api/error.ts

The error message was indicating the user to use `--documentation`
argument which doesn't exist, it should be `--doc`.

fix: error message when documentation is not found

---

package-lock.json
package.json
src/definition.ts
typings.d.ts

This commit makes sure to update the minimal version of the
`@asyncapi/spec` package which was locked to a version supporting
asyncapi 2.6.0, but not changed in the package.json file.
With this commit we make sure to always support asyncapi 2.6.0 even
for already existing installation (or cli used as a lib - in the
github-action for example).

deps: make sure to force the minimum version of AsyncAPI spec

---

src/commands/preview.ts
test/commands/preview.test.ts

This commit makes sure to only create one preview (the previous
tentative fix on live previews would create 1 preview, then a 2nd
preview, and then update that 2nd preview).
Follow-up to #456 (cf #182)

preview: fix (again) the “live preview” feature

---

README.md

This new readme is also intented to land on docs.bump.sh/help

readme: rewrite the readme for a better help documentation

---

README.md
examples/valid/openapi.v3.json
examples/valid/overlay.yaml
package-lock.json
package.json
src/args.ts
src/commands/deploy.ts
src/commands/overlay.ts
src/core/deploy.ts
src/core/overlay.ts
src/definition.ts
src/flags.ts
src/index.ts
test/commands/overlay.test.ts
test/unit/definition.test.ts
typings.d.ts

Together with the [guide written by Phil on OpenAPI overlays](https://github.com/bump-sh/docs/pull/153), we thought it would be a good idea to release a new `bump overlay` command in the CLI in order to test the new [OpenAPI Overlay specification](https://github.com/OAI/Overlay-Specification).
This WIP change is based on [@lornajane's work on overlays](https://github.com/lornajane/openapi-overlays-js) with a few changes [here](https://github.com/lornajane/openapi-overlays-js/pull/8) and [there](https://github.com/lornajane/openapi-overlays-js/pull/9).
I've published the resulting built package from this branch as **a beta version on npmjs registry so you can test a beta version of Bump CLI installable** with:
```
npm install bump-cli@beta
```
---
**Example usage**
- Wrong overlay file
``` …
```

Add a new `overlay` command to be able to apply OpenAPI overlays on given API document

---

src/commands/deploy.ts

This commit improves the error message when no documentations are
found in the target directory to deploy by providing the filename
pattern valued used by the CLI to find doc files.

deploy: better error message when no docs found in directory deploy

---

src/core/diff.ts
test/commands/diff.test.ts

We decided in the past to hard code a 30s timeout for a diff within
the CLI, but this is quite problematic especially if we have too much
traffic at the same time.
Until we have more power in our queuing system, I believe it's best to
allow a bit more time before failing.
This commit increases the timeout value by 3. Going from 30seconds to
2 minutes.

diff: increase timeout to 2min

---

src/core/overlay.ts

This commit is a backport of
https://github.com/lornajane/openapi-overlays-js/pull/13/files.
To fix the issue of applying `remove` action on a target which is a
list. Before the fix it would remove only the first occurence of the
target. With this fix it removes all the occurences of the target
JSONPath.
Thanks @lcawl for reporting the issue!

fix(overlay): backport of an upstream fix for remove action

---

src/core/diff.ts
test/commands/diff.test.ts

This change adapts the detection of the response of the /versions API
to check any of the existing formats for a content rather than only
checking the `version.diff_summary` field.
This will help to be able to return an empty array `[]` when asking
for the `--format json` (since we fixed the API return values last
week in https://github.com/bump-sh/bump/pull/5703)

diff: make sure to parse versions API response with any format diff

---

package-lock.json
package.json

We remove this oclif plugin for now as it's not compatible with the
old version of oclif we are using:
```
> npx bump --version
bump-cli/2.8.3 linux-x64 node-v18.18.1
(node:51608) [ERR_REQUIRE_ESM] Error Plugin: bump-cli [ERR_REQUIRE_ESM]: require() of ES Module /home/paul/devel/bump-sh/bump/node_modules/@oclif/plugin-warn-if-update-available/lib/hooks/init/check-update.js from /home/paul/devel/bump-sh/bump/node_modules/@oclif/config/lib/config.js not supported.
Instead change the require of check-update.js in /home/paul/devel/bump-sh/bump/node_modules/@oclif/config/lib/config.js to a dynamic import() which is available in all CommonJS modules.
module: @oclif/config@1.18.17
task: runHook init
plugin: bump-cli
root: /home/paul/devel/bump-sh/bump/node_modules/bump-cli
See more details with …
```

deps: temporarily remove 'warn-if-update-available' package

---

README.md

The file 'icon-default-large.png' has been removed from the Bump code base, duplication of 'icon-default-maskable-large.png'

Rebrand: Update Readme logo

---

examples/invalid/asyncapi.yml
examples/invalid/openapi.yml
examples/valid/bump-api.json
examples/valid/openapi.v3.json
package.json
src/commands/deploy.ts

Small contribution to the tool, noticed by reviewing big PR #587 
When we mention the cli itself, name is indeed 'bump'.
But I favored bump.sh each time we mention the organization behind this tool.

Favor name  bump.sh

---

package.json
src/api/index.ts
src/commands/diff.ts
src/core/diff.ts

This is a fix after the major upgrade of the CLI (in #587) where we
broke the interface of the exported core `Diff` class and made its
usage as a lib more complicated.
Let's align back to what it used to be, and even simplify the
interface by making the constructor argument optional.

fix: align exported core Diff interface with previous 2.8 signature

---

README.md
examples/valid/overlay2.yaml
src/commands/deploy.ts
src/core/deploy.ts
src/definition.ts
src/flags.ts
test/commands/deploy.test.ts

This adds the ability for the deploy command to take multiple `--overlay` flags.
```
node ./bin/run.js deploy examples/valid/openapi.v3.json 
--overlay=examples/valid/overlay.yaml 
--overlay=examples/valid/overlay2.yaml
```
This was done to make life easier on the Speakeasy workflow, which will need us to apply one overlay for each SDK language produced, of which there may be many. It looks a bit like this at the moment, and keeping track of `openapi.codegen1.yaml` and `openapi.codegen2.yaml` is going to be frustrating.
```
- name: Add TypeScript SDK Samples to OpenAPI
run: |
npx bump-cli overlay openapi.yaml \
https://spec.speakeasy.com/bumpsh/bumpsh/train-travel-api-typescript-code-samples \
> openapi.codegen1.yaml
- name: Add PHP SDK Samples to OpenAPI
run: |
npx bump-cli overlay …
```

feat: apply multiple overlays on deploy

---

README.md
src/commands/diff.ts
src/flags.ts
test/commands/diff.test.ts

This commit adds a `--no-*` version of the `--fail-on-breaking` flag
on the diff command to be able to disable the default behavior within
CI enviroments (where CI=1 env var is set for instance). Indeed, in
those environment the flag was always forced to true (without being
well documented) until now.
About #623

diff: add a `--no-fail-on-breaking` flag

---

README.md

- **docs: fix link to github action**
- **docs: tidied up the README a little**

readme tidy

---

package-lock.json
package.json
src/core/overlay.ts
test/unit/definition.test.ts

The currently used `jsonpath` lib is pretty old and unmaintained (last
commits 4 years ago), and even more problematic it causes issues to
[upgrade our github action](https://github.com/bump-sh/github-action/pull/508) as that lib has an inconsistant use of
'require' and doesn't seem to work well with the packaging
step (rollup) of the github action.
Hopefully this upgrade (and change of lib) should let us a clean
upgrade of the GH action to an ESM version 🤞
As I re-wrote the way we apply overlays I also took the opportunity to fix #588 in this change.

overlay: replace `jsonpath` by the more recent (and typed) `jsonpathly`

---

src/core/utils/file.ts
test/commands/deploy.test.ts

Improved `isDir`: Now handles HTTP(S) URLs by excluding them as directories.
Added `isHttpUrl` function: Detects whether a given path is an HTTP(S) URL.
Better error handling: Uses `CLIError` to prevent crashes on statSync errors.

Add isHttpUrl check and enhance error handling

---

src/core/diff.ts
test/unit/api.test.ts

I noticed that `Config.load('../../')` was not enough in my environment, and was loading an incorrect directory, starting from the projet directory instead of the current file directory.
---
noticed by working on #679

Improve config load with resolve

---

README.md

Mention how to run and use CLI in local environment.
Bonus: 2nd commit upgrade bump-cli version in README to 2.9.3

Readme: Add instructions to run CLI in local environment

---

examples/valid/openapi.v3.json
examples/valid/overlay.yaml
src/core/overlay.ts
test/commands/overlay.test.ts

These two cases (updating the root object, and, updating the first element of an array) was not tested in our unit tests and were both broken by the previous overlay core refactoring (#673). 🤯
Thanks a lot to @lcawl for reporting this issue 🙇
Closes https://github.com/bump-sh/bump/issues/6579

fix(overlay): make sure root updates and array[0] updates work

---

src/api/models.ts
src/commands/deploy.ts
src/core/deploy.ts
src/flags.ts
test/commands/deploy.test.ts

Allow user to deploy a new version  temporary, deployed in the context of the API (logo, CSS, group by tag/path ...).
In this commit, we add a new tag `--preview`,
that can be added to `bump deploy` command.
Output is a temporary version, accessible by a link
visible in CLI response, and invisible in deployment list on Bump.sh workspace.
As described here: https://github.com/bump-sh/cli/issues/381#issuecomment-2724350235
---
following #381

Add flag '--preview' to Deploy command

---

examples/valid/openapi.v3.json
src/core/overlay.ts

With the refactoring made on the overlay command in
[v2.9.3](https://github.com/bump-sh/cli/releases/tag/v2.9.3) we
introduced a bug when `remove`ing elements if the overlay action was
targeting an array.
This was due to the exploded json paths which contains indexes, and
that those index change each time we remove an element.
We've fixed the bug with @AurelDbs by iterating over the list of paths
in a reversed order (we start by the end of the array instead of the
beginning).
_Note: once again, thanks @lcawl for reporting this issue! And sorry
for the unexpected behavior 🙂_

fix(overlay): fix removal of elements of an array

---

examples/valid/overlay.yaml
src/definition.ts
test/commands/overlay.test.ts

Fixes #708
When outputing the overlayed result of the `bump overlay` command, we
shouldn't export yaml aliases (`*ref` used with `&ref`) as this
feature of YAML is not well supported by tools.
Also, it's not the job of the overlay command to guess whether to use
YAML anchors or not.
With this commit we make sure to output yaml without refs.

fix(overlay): don't output yaml anchors

---

examples/valid/doc/error-codes.md
examples/valid/overlay.yaml
src/definition.ts
test/commands/overlay.test.ts
test/unit/definition.test.ts

This commit is a fix to be able to keep track of references ($ref)
used inside an overlay. This make it possible to use an overlay which
references external files, and have them available for the
main (overlayed) definition.
Thanks @JakeSCahill for noticing the bug!

fix(overlay): make sure to keep track of overlay $refs
